In [1]:
import numpy as np
import pandas as pd

from tqdm import tqdm

In [2]:
main_dir = "competitive-data-science-predict-future-sales"

In [3]:
X = np.load(f"{main_dir}/X.npy")
print(X.shape)
X

(214200, 5, 33)


array([[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.00000000e+00, 3.00000000e+00, 1.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.49900000e+03, 9.99166667e+02, 7.49500000e+02],
        [1.90000000e+01, 1.90000000e+01, 1.90000000e+01, ...,
         1.90000000e+01, 1.90000000e+01, 1.90000000e+01],
        [5.00000000e+00, 5.00000000e+00, 5.00000000e+00, ...,
         5.00000000e+00, 5.00000000e+00, 5.00000000e+00],
        [5.03700000e+03, 5.03700000e+03, 5.03700000e+03, ...,
         5.03700000e+03, 5.03700000e+03, 5.03700000e+03]],

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [5.50000000e+01, 5.50000000e+01, 5.50000000e+01, ...,
         5.50000000e+01, 5.50000000e+01, 5.50000000e+01],
        [5.00000000e+00, 5.00000000e+0

In [4]:
Y = np.load(f"{main_dir}/Y.npy")
# Y = Y.reshape((214200,1))
print(Y.shape)
Y

(214200,)


array([0, 0, 1, ..., 0, 0, 0])

In [5]:
X[0].shape

(5, 33)

In [6]:
gg0 = np.array([Y[0], 0, X[0][2][0], X[0][3][0], X[0][4][0]])
gg1 = np.array([Y[1], 0, X[1][2][0], X[1][3][0], X[1][4][0]])
gg = np.append(gg0, gg1).reshape(2,5,1)
gg

array([[[0.000e+00],
        [0.000e+00],
        [1.900e+01],
        [5.000e+00],
        [5.037e+03]],

       [[0.000e+00],
        [0.000e+00],
        [5.500e+01],
        [5.000e+00],
        [5.320e+03]]])

In [7]:
gg0.shape

(5,)

In [8]:
ty = np.append(np.empty((0,5)), gg0)
ty = np.append(ty, gg1).reshape(2,5,1)
ty

array([[[0.000e+00],
        [0.000e+00],
        [1.900e+01],
        [5.000e+00],
        [5.037e+03]],

       [[0.000e+00],
        [0.000e+00],
        [5.500e+01],
        [5.000e+00],
        [5.320e+03]]])

In [9]:
X[0].shape

(5, 33)

In [10]:
bg0 = np.concatenate([X[0], gg0.reshape(5,1)], axis=1)
print(bg0.shape)
bg0

(5, 34)


array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.00000000e+00,
        2.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.59900000e+03,

In [11]:
for i, r in enumerate(X):
    if i == 0:
        print(r)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 0.00000000e+00 1.00000000e+00 2.00000000e+00
  2.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 3.00000000e+00
  1.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  2.59900000e+03 0.00000000e+00 2.59900000e+03 1.99900000e+03
  1.99900000e+03 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.29900000e+03 1.49900000e+03 1.49900000e+03 9.991

In [12]:
# dgh = 

In [13]:
# combine x and y for normalizing

def combine_x_y(x, y):
    ww = []
    for i in tqdm(range(len(x))):
        ggi = [y[i], 0, x[i][2][0], x[i][3][0], x[i][4][0]]
        ww.append(ggi)
    ww = np.array(ww).reshape(214200, 5, 1)
    bg = np.concatenate([x, ww], axis=2)
    return bg

In [14]:
combined = combine_x_y(X, Y)
print(combined.shape)
combined

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 214200/214200 [00:00<00:00, 927907.90it/s]


(214200, 5, 34)


array([[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         3.00000000e+00, 1.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         9.99166667e+02, 7.49500000e+02, 0.00000000e+00],
        [1.90000000e+01, 1.90000000e+01, 1.90000000e+01, ...,
         1.90000000e+01, 1.90000000e+01, 1.90000000e+01],
        [5.00000000e+00, 5.00000000e+00, 5.00000000e+00, ...,
         5.00000000e+00, 5.00000000e+00, 5.00000000e+00],
        [5.03700000e+03, 5.03700000e+03, 5.03700000e+03, ...,
         5.03700000e+03, 5.03700000e+03, 5.03700000e+03]],

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [5.50000000e+01, 5.50000000e+01, 5.50000000e+01, ...,
         5.50000000e+01, 5.50000000e+01, 5.50000000e+01],
        [5.00000000e+00, 5.00000000e+0

In [15]:
tt = np.concatenate([np.random.rand(214200,5,33), np.random.rand(214200,5,1)], axis=2)
print(tt.shape)
tt

(214200, 5, 34)


array([[[0.74129008, 0.50288061, 0.57195263, ..., 0.67201523,
         0.5422169 , 0.04416988],
        [0.19635885, 0.16725543, 0.74825342, ..., 0.52798506,
         0.9973772 , 0.28385463],
        [0.45474189, 0.10055958, 0.31188647, ..., 0.04438378,
         0.03092295, 0.85320063],
        [0.45290526, 0.37982461, 0.0926447 , ..., 0.65721202,
         0.63570395, 0.8968888 ],
        [0.39361597, 0.69103199, 0.81322833, ..., 0.37866516,
         0.79557578, 0.47082851]],

       [[0.52471413, 0.08487752, 0.31395327, ..., 0.95976063,
         0.10269   , 0.26265717],
        [0.61395874, 0.78478542, 0.31984689, ..., 0.07490043,
         0.17399504, 0.85762469],
        [0.08457271, 0.9560149 , 0.80869034, ..., 0.84182578,
         0.21733044, 0.54129625],
        [0.40622636, 0.43394292, 0.35787367, ..., 0.81105007,
         0.34489195, 0.33260735],
        [0.04983385, 0.68190861, 0.48285778, ..., 0.48324282,
         0.26587627, 0.38598203]],

       [[0.70802952, 0.75365322, 0.6

In [20]:
c_min = combined.min(axis=(1, 2), keepdims=True)
c_max = combined.max(axis=(1, 2), keepdims=True)

c_n = (combined - c_min)/(c_max - c_min)

print(c_n.shape)
c_n

(214200, 5, 34)


array([[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         5.95592615e-04, 1.98530872e-04, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.98365429e-01, 1.48798888e-01, 0.00000000e+00],
        [3.77208656e-03, 3.77208656e-03, 3.77208656e-03, ...,
         3.77208656e-03, 3.77208656e-03, 3.77208656e-03],
        [9.92654358e-04, 9.92654358e-04, 9.92654358e-04, ...,
         9.92654358e-04, 9.92654358e-04, 9.92654358e-04],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
         1.00000000e+00, 1.00000000e+00, 1.00000000e+00]],

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [1.03383459e-02, 1.03383459e-02, 1.03383459e-02, ...,
         1.03383459e-02, 1.03383459e-02, 1.03383459e-02],
        [9.39849624e-04, 9.39849624e-0

In [26]:
print(c_min.shape, c_max.shape)
print(c_min, c_max)

(214200, 1, 1) (214200, 1, 1)
[[[0.]]

 [[0.]]

 [[0.]]

 ...

 [[0.]]

 [[0.]]

 [[0.]]] [[[ 5037.]]

 [[ 5320.]]

 [[ 5233.]]

 ...

 [[15757.]]

 [[19648.]]

 [[  969.]]]


In [17]:
sum_of_rows = combined.sum(axis=0)
normalized_array = combined / sum_of_rows[np.newaxis, :]
print(normalized_array.shape)
normalized_array

(214200, 5, 34)


/var/folders/qx/m5twkz1d4x59mlkfs6y0_z1h0000gn/T/ipykernel_1209/2984180187.py:2: RuntimeWarning: invalid value encountered in true_divide
  normalized_array = combined / sum_of_rows[np.newaxis, :]


array([[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         5.03550028e-05, 1.69998640e-05, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         3.62710610e-05, 2.58227669e-05,            nan],
        [1.91541565e-06, 1.91541565e-06, 1.91541565e-06, ...,
         1.91541565e-06, 1.91541565e-06, 1.91541565e-06],
        [7.37691615e-07, 7.37691615e-07, 7.37691615e-07, ...,
         7.37691615e-07, 7.37691615e-07, 7.37691615e-07],
        [2.13400086e-06, 2.13400086e-06, 2.13400086e-06, ...,
         2.13400086e-06, 2.13400086e-06, 2.13400086e-06]],

       [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00,            nan],
        [5.54462424e-06, 5.54462424e-06, 5.54462424e-06, ...,
         5.54462424e-06, 5.54462424e-06, 5.54462424e-06],
        [7.37691615e-07, 7.37691615e-0

In [18]:
from sklearn.preprocessing import normalize

In [19]:
normalized_array = normalize(combined, axis=1, norm='max')
print(normalized_array.shape)
normalized_array

ValueError: Found array with dim 3. the normalize function expected <= 2.